version: 2.1

jobs:
    build-image: 
      environment: 
        IMAGE_NAME: devtest/image-on-cci
      docker:
        - image: circleci/buildpack-deps:stretch
      steps:
        - checkout
        - setup_remote_docker
        - run:
            name: Build Docker Image
            command: docker build -t $IMAGE_NAME:latest        

workflows:
  test-deploy:
    jobs: 
      - build-image:
          filters:
            branches:
              only: main
        
